lib-target:
	cd CommunicationServer; make lib-target

lib-host:
	cd CommunicationServer; make lib-host

target:
	cd CommunicationServer; make target

host:
	cd CommunicationServer; make host

test: 
	cd CommunicationServer; make test

all:
	cd CommunicationServer; make all

clean:
	cd CommunicationServer; make clean