lib-target:
	cd CommunicationServer; make lib-target

lib-host:
	cd CommunicationServer; make lib-host

target:
	cd CommunicationServer; make target

host:
	cd CommunicationServer; make host

lib-host-gcov:
	cd CommunicationServer; make lib-host-gcov

host-gcov:
	cd CommunicationServer; make host-gcov

test: 
	cd CommunicationServer; make test

test-run: 
	cd CommunicationServer; make test-run

test-clean: 
	cd CommunicationServer; make test-clean

copy:
	cd CommunicationServer; make copy

all:
	make lib-target
	make lib-host
	make target
	make host

clean:
	cd CommunicationServer; make clean