#include "gtest/gtest.h"
#include "../Plate.h"
#include <string>
 
#define PLATEID 1
#define PLATEDRIVEPOSITION 2
#define PLATECOLLIMATORPOSITION 3
#define PLATEPROPERTIES "properties"
#define PLATETHICKNESS 5

TEST(NewPlate, GetPlateID) 
{
	Plate plate(PLATEID,PLATEDRIVEPOSITION,PLATECOLLIMATORPOSITION,PLATEPROPERTIES,PLATETHICKNESS);
    EXPECT_EQ(PLATEID, plate.GetID());
}
TEST(NewPlate, GetDrivePosition) 
{
	Plate plate(PLATEID,PLATEDRIVEPOSITION,PLATECOLLIMATORPOSITION,PLATEPROPERTIES,PLATETHICKNESS);
    EXPECT_EQ(PLATEDRIVEPOSITION, plate.GetDrivePosition());
}
TEST(NewPlate, GetColimatorPosition) 
{
	Plate plate(PLATEID,PLATEDRIVEPOSITION,PLATECOLLIMATORPOSITION,PLATEPROPERTIES,PLATETHICKNESS);
    EXPECT_EQ(PLATECOLLIMATORPOSITION, plate.GetCollimatorPosition());
}
TEST(NewPlate, GetProperties) 
{
	Plate plate(PLATEID,PLATEDRIVEPOSITION,PLATECOLLIMATORPOSITION,PLATEPROPERTIES,PLATETHICKNESS);
    EXPECT_EQ(PLATEPROPERTIES, plate.GetProperties());
}
TEST(NewPlate, GetThickness) 
{
	Plate plate(PLATEID,PLATEDRIVEPOSITION,PLATECOLLIMATORPOSITION,PLATEPROPERTIES,PLATETHICKNESS);
    EXPECT_EQ(PLATETHICKNESS, plate.GetThickness());
}